const EMOJI_DATA = {
    smileys: [
        { char: "😀", name: "grinning face" },
        { char: "😃", name: "smiling face with open mouth" },
        { char: "😄", name: "smiling face with open mouth and smiling eyes" },
        { char: "😁", name: "grinning face with smiling eyes" },
        { char: "😆", name: "smiling face with open mouth and closed eyes" },
        { char: "😅", name: "smiling face with open mouth and cold sweat" },
        { char: "😂", name: "face with tears of joy" },
        { char: "🤣", name: "rolling on the floor laughing" },
        { char: "😊", name: "smiling face with smiling eyes" },
        { char: "😇", name: "smiling face with halo" },
        { char: "🙂", name: "slightly smiling face" },
        { char: "🙃", name: "upside-down face" },
        { char: "😉", name: "winking face" },
        { char: "😌", name: "relieved face" },
        { char: "😍", name: "smiling face with heart-eyes" },
        { char: "😘", name: "face throwing a kiss" },
        { char: "😗", name: "kissing face" },
        { char: "😙", name: "kissing face with smiling eyes" },
        { char: "😚", name: "kissing face with closed eyes" },
        { char: "😋", name: "face savoring delicious food" },
        { char: "😛", name: "face with stuck-out tongue" },
        { char: "😜", name: "face with stuck-out tongue and winking eye" },
        { char: "😝", name: "face with stuck-out tongue and closed eyes" },
        { char: "🤑", name: "money-mouth face" },
        { char: "🤗", name: "hugging face" },
        { char: "🤓", name: "nerd face" },
        { char: "😎", name: "smiling face with sunglasses" },
        { char: "🤡", name: "clown face" },
        { char: "🤠", name: "cowboy hat face" },
        { char: "😏", name: "smirking face" },
        { char: "😒", name: "unamused face" },
        { char: "😞", name: "disappointed face" },
        { char: "😔", name: "pensive face" },
        { char: "worried", name: "worried face" },
        { char: "😕", name: "confused face" },
        { char: "🙁", name: "slightly frowning face" },
        { char: "😣", name: "persevering face" },
        { char: "😖", name: "confounded face" },
        { char: "😫", name: "tired face" },
        { char: "😩", name: "weary face" },
        { char: "😤", name: "face with steam from nose" },
        { char: "😠", name: "angry face" },
        { char: "😡", name: "pouting face" },
        { char: "😶", name: "face without mouth" },
        { char: "😐", name: "neutral face" },
        { char: "😑", name: "expressionless face" },
        { char: "😯", name: "hushed face" },
        { char: "😦", name: "frowning face with open mouth" },
        { char: "😧", name: "anguished face" },
        { char: "😮", name: "face with open mouth" },
        { char: "😲", name: "astonished face" },
        { char: "😵", name: "dizzy face" },
        { char: "😳", name: "flushed face" },
        { char: "😱", name: "face screaming in fear" },
        { char: "😨", name: "fearful face" },
        { char: "😰", name: "face with open mouth and cold sweat" },
        { char: "😢", name: "crying face" },
        { char: "😥", name: "disappointed but relieved face" },
        { char: "🤤", name: "drooling face" },
        { char: "😭", name: "loudly crying face" },
        { char: "😓", name: "face with cold sweat" },
        { char: "😪", name: "sleepy face" },
        { char: "😴", name: "sleeping face" },
        { char: "🙄", name: "face with rolling eyes" },
        { char: "🤔", name: "thinking face" },
        { char: "🤥", name: "lying face" },
        { char: "🤐", name: "zipper-mouth face" },
        { char: "🤢", name: "nauseated face" },
        { char: "🤧", name: "sneezing face" },
        { char: "😷", name: "face with medical mask" },
        { char: "🤒", name: "face with thermometer" },
        { char: "🤕", name: "face with head-bandage" },
        { char: "👿", name: "angry face with horns" },
        { char: "😈", name: "smiling face with horns" },
        { char: "💀", name: "skull" },
        { char: "☠️", name: "skull and crossbones" },
        { char: "💩", name: "pile of poo" },
        { char: "👋", name: "waving hand" },
        { char: "🤚", name: "raised back of hand" },
        { char: "🖐️", name: "hand with fingers splayed" },
        { char: "✋", name: "raised hand" },
        { char: "🖖", name: "vulcan salute" },
        { char: "👌", name: "OK hand" },
        { char: "🤏", name: "pinching hand" },
        { char: "✌️", name: "victory hand" },
        { char: "🤞", name: "crossed fingers" },
        { char: "🤟", name: "love-you gesture" },
        { char: "🤘", name: "sign of the horns" },
        { char: "🤙", name: "call me hand" },
        { char: "👈", name: "backhand index pointing left" },
        { char: "👉", name: "backhand index pointing right" },
        { char: "👆", name: "backhand index pointing up" },
        { char: "👇", name: "backhand index pointing down" },
        { char: "☝️", name: "index pointing up" },
        { char: "👍", name: "thumbs up" },
        { char: "👎", name: "thumbs down" },
        { char: "✊", name: "raised fist" },
        { char: "👊", name: "oncoming fist" },
        { char: "🤛", name: "left-facing fist" },
        { char: "🤜", name: "right-facing fist" },
        { char: "👏", name: "clapping hands" },
        { char: "🙌", name: "raising hands" },
        { char: "👐", name: "open hands" },
        { char: "🤲", name: "palms up together" },
        { char: "🤝", name: "handshake" },
        { char: "🙏", name: "folded hands" },
        { char: "💪", name: "flexed biceps" },
        { char: "🧠", name: "brain" },
        { char: "❤️", name: "red heart" },
        { char: "🧡", name: "orange heart" },
        { char: "💛", name: "yellow heart" },
        { char: "💚", name: "green heart" },
        { char: "💙", name: "blue heart" },
        { char: "💜", name: "purple heart" },
        { char: "🖤", name: "black heart" },
        { char: "🤍", name: "white heart" },
        { char: "🤎", name: "brown heart" },
        { char: "💔", name: "broken heart" }
    ],
    animals: [
        { char: "🐶", name: "dog face" },
        { char: "🐱", name: "cat face" },
        { char: "🐭", name: "mouse face" },
        { char: "🐹", name: "hamster face" },
        { char: "🐰", name: "rabbit face" },
        { char: "🦊", name: "fox face" },
        { char: "🐻", name: "bear face" },
        { char: "🐼", name: "panda face" },
        { char: "🐨", name: "koala" },
        { char: "🐯", name: "tiger face" },
        { char: "🦁", name: "lion face" },
        { char: "🐮", name: "cow face" },
        { char: "🐷", name: "pig face" },
        { char: "🐽", name: "pig nose" },
        { char: "🐸", name: "frog face" },
        { char: "🐵", name: "monkey face" },
        { char: "🐔", name: "chicken" },
        { char: "🐧", name: "penguin" },
        { char: "🐦", name: "bird" },
        { char: "🐤", name: "baby chick" },
        { char: "🐣", name: "hatching chick" },
        { char: "🐥", name: "front-facing baby chick" },
        { char: "🦆", name: "duck" },
        { char: "🦅", name: "eagle" },
        { char: "🦉", name: "owl" },
        { char: "🦇", name: "bat" },
        { char: "🐺", name: "wolf" },
        { char: "🐗", name: "boar" },
        { char: "🐴", name: "horse face" },
        { char: "🦄", name: "unicorn" },
        { char: "🐝", name: "honeybee" },
        { char: "🐛", name: "bug" },
        { char: "🦋", name: "butterfly" },
        { char: "🐌", name: "snail" },
        { char: "🐞", name: "lady beetle" },
        { char: "🐜", name: "ant" },
        { char: "🦗", name: "cricket" },
        { char: "🕷️", name: "spider" },
        { char: "🕸️", name: "spider web" },
        { char: "🦂", name: "scorpion" },
        { char: "🐢", name: "turtle" },
        { char: "🐍", name: "snake" },
        { char: "🦎", name: "lizard" },
        { char: "🦖", name: "T-Rex" },
        { char: "🦕", name: "sauropod" },
        { char: "🐙", name: "octopus" },
        { char: "🦑", name: "squid" },
        { char: "🦐", name: "shrimp" },
        { char: "🦞", name: "lobster" },
        { char: "🦀", name: "crab" },
        { char: "🐡", name: "blowfish" },
        { char: "🐠", name: "tropical fish" },
        { char: "🐟", name: "fish" },
        { char: "🐬", name: "dolphin" },
        { char: "🐳", name: "spouting whale" },
        { char: "🐋", name: "whale" },
        { char: "🦈", name: "shark" },
        { char: "🐊", name: "crocodile" },
        { char: "🐅", name: "tiger" },
        { char: "🐆", name: "leopard" },
        { char: "🦓", name: "zebra" },
        { char: "🦍", name: "gorilla" },
        { char: "🐘", name: "elephant" },
        { char: "🦛", name: "hippopotamus" },
        { char: "🦏", name: "rhinoceros" },
        { char: "🐪", name: "camel" },
        { char: "🐫", name: "two-hump camel" },
        { char: "🦒", name: "giraffe" },
        { char: "🦘", name: "kangaroo" },
        { char: "🐃", name: "water buffalo" },
        { char: "🐂", name: "ox" },
        { char: "🐄", name: "cow" },
        { char: "🐎", name: "horse" },
        { char: "🐖", name: "pig" },
        { char: "🐏", name: "ram" },
        { char: "🐑", name: "sheep" },
        { char: "🦙", name: "llama" },
        { char: "🐐", name: "goat" },
        { char: "🦌", name: "deer" },
        { char: "🐕", name: "dog" },
        { char: "🐩", name: "poodle" },
        { char: "🐈", name: "cat" },
        { char: "🐓", name: "rooster" },
        { char: "🦃", name: "turkey" },
        { char: "🕊️", name: "dove" },
        { char: "🐇", name: "rabbit" },
        { char: "🐁", name: "mouse" },
        { char: "🐀", name: "rat" },
        { char: "🐿️", name: "chipmunk" },
        { char: "🦔", name: "hedgehog" }
    ],
    food: [
        { char: "🍇", name: "grapes" },
        { char: "🍈", name: "melon" },
        { char: "🍉", name: "watermelon" },
        { char: "🍊", name: "tangerine" },
        { char: "🍋", name: "lemon" },
        { char: "🍌", name: "banana" },
        { char: "🍍", name: "pineapple" },
        { char: "🍎", name: "red apple" },
        { char: "🍏", name: "green apple" },
        { char: "🍐", name: "pear" },
        { char: "🍑", name: "peach" },
        { char: "🍒", name: "cherries" },
        { char: "🍓", name: "strawberry" },
        { char: "🥝", name: "kiwi fruit" },
        { char: "🍅", name: "tomato" },
        { char: "🥥", name: "coconut" },
        { char: "🥑", name: "avocado" },
        { char: "🍆", name: "eggplant" },
        { char: "🥔", name: "potato" },
        { char: "🥕", name: "carrot" },
        { char: "🌽", name: "ear of corn" },
        { char: "🌶️", name: "hot pepper" },
        { char: "🥒", name: "cucumber" },
        { char: "🥬", name: "leafy green" },
        { char: "🥦", name: "broccoli" },
        { char: "🍄", name: "mushroom" },
        { char: "🥜", name: "peanuts" },
        { char: "🌰", name: "chestnut" },
        { char: "🍞", name: "bread" },
        { char: "🥐", name: "croissant" },
        { char: "🥖", name: "baguette bread" },
        { char: "🥨", name: "pretzel" },
        { char: "🥯", name: "bagel" },
        { char: "🥞", name: "pancakes" },
        { char: "🧀", name: "cheese wedge" },
        { char: "🍖", name: "meat on bone" },
        { char: "🍗", name: "poultry leg" },
        { char: "🥩", name: "cut of meat" },
        { char: "🥓", name: "bacon" },
        { char: "🍔", name: "hamburger" },
        { char: "🍟", name: "french fries" },
        { char: "🍕", name: "pizza" },
        { char: "🌭", name: "hot dog" },
        { char: "🥪", name: "sandwich" },
        { char: "🌮", name: "taco" },
        { char: "🌯", name: "burrito" },
        { char: "🥙", name: "stuffed flatbread" },
        { char: "🥚", name: "egg" },
        { char: "🍳", name: "cooking" },
        { char: "🥘", name: "shallow pan of food" },
        { char: "🍲", name: "pot of food" },
        { char: "🥣", name: "bowl with spoon" },
        { char: "🥗", name: "green salad" },
        { char: "🍿", name: "popcorn" },
        { char: "🧂", name: "salt" },
        { char: "🥫", name: "canned food" },
        { char: "🍱", name: "bento box" },
        { char: "🍘", name: "rice cracker" },
        { char: "🍙", name: "rice ball" },
        { char: "🍚", name: "cooked rice" },
        { char: "🍛", name: "curry rice" },
        { char: "🍜", name: "steaming bowl" },
        { char: "🍝", name: "spaghetti" },
        { char: "🍠", name: "roasted sweet potato" },
        { char: "🍢", name: "oden" },
        { char: "🍣", name: "sushi" },
        { char: "🍤", name: "fried shrimp" },
        { char: "🍥", name: "fish cake with swirl" },
        { char: "🥮", name: "moon cake" },
        { char: "🍡", name: "dango" },
        { char: "🥟", name: "dumpling" },
        { char: "🥠", name: "fortune cookie" },
        { char: "🥡", name: "takeout box" },
        { char: "🍦", name: "soft ice cream" },
        { char: "🍧", name: "shaved ice" },
        { char: "🍨", name: "ice cream" },
        { char: "🍩", name: "doughnut" },
        { char: "🍪", name: "cookie" },
        { char: "🎂", name: "birthday cake" },
        { char: "🍰", name: "shortcake" },
        { char: "🧁", name: "cupcake" },
        { char: "🥧", name: "pie" },
        { char: "🍫", name: "chocolate bar" },
        { char: "🍬", name: "candy" },
        { char: "🍭", name: "lollipop" },
        { char: "🍮", name: "custard" },
        { char: "🍯", name: "honey pot" },
        { char: "🍼", name: "baby bottle" },
        { char: "🥛", name: "glass of milk" },
        { char: "☕", name: "hot beverage" },
        { char: "🍵", name: "teacup without handle" },
        { char: "🍶", name: "sake" },
        { char: "🍾", name: "bottle with popping cork" },
        { char: "🍷", name: "wine glass" },
        { char: "🍸", name: "cocktail glass" },
        { char: "🍹", name: "tropical drink" },
        { char: "🍺", name: "beer mug" },
        { char: "🍻", name: "clinking beer mugs" },
        { char: "🥂", name: "clinking glasses" },
        { char: "🥃", name: "tumbler glass" },
        { char: "🥤", name: "cup with straw" }
    ],
    activities: [
        { char: "⚽", name: "soccer ball" },
        { char: "🏀", name: "basketball" },
        { char: "🏈", name: "american football" },
        { char: "⚾", name: "baseball" },
        { char: "🥎", name: "softball" },
        { char: "🎾", name: "tennis" },
        { char: "🏐", name: "volleyball" },
        { char: "🏉", name: "rugby football" },
        { char: "🥏", name: "flying disc" },
        { char: "🎱", name: "pool 8 ball" },
        { char: "🏓", name: "ping pong" },
        { char: "🏸", name: "badminton" },
        { char: "🥅", name: "goal net" },
        { char: "🏒", name: "ice hockey" },
        { char: "🏑", name: "field hockey" },
        { char: "🥍", name: "lacrosse" },
        { char: "🏏", name: "cricket game" },
        { char: "⛳", name: "flag in hole" },
        { char: "🏹", name: "bow and arrow" },
        { char: "🎣", name: "fishing pole" },
        { char: "🥊", name: "boxing glove" },
        { char: "🥋", name: "martial arts uniform" },
        { char: "🎽", name: "running shirt" },
        { char: "⛸️", name: "ice skate" },
        { char: "🥌", name: "curling stone" },
        { char: "🛷", name: "sled" },
        { char: "🎿", name: "skis" },
        { char: "🎳", name: "bowling" },
        { char: "🎮", name: "video game" },
        { char: "🎰", name: "slot machine" },
        { char: "🎲", name: "game die" },
        { char: "🧩", name: "puzzle piece" },
        { char: "♟️", name: "chess pawn" },
        { char: "🎭", name: "performing arts" },
        { char: "🎨", name: "artist palette" },
        { char: "🧵", name: "thread" },
        { char: "🧶", name: "yarn" }
    ],
    travel: [
        { char: "🚗", name: "automobile" },
        { char: "🚕", name: "taxi" },
        { char: "🚙", name: "sport utility vehicle" },
        { char: "🚌", name: "bus" },
        { char: "🚎", name: "trolleybus" },
        { char: "🏎️", name: "racing car" },
        { char: "🚓", name: "police car" },
        { char: "🚑", name: "ambulance" },
        { char: "🚒", name: "fire engine" },
        { char: "🚐", name: "minibus" },
        { char: "🚚", name: "delivery truck" },
        { char: "🚛", name: "articulated lorry" },
        { char: "🚜", name: "tractor" },
        { char: "🏍️", name: "motorcycle" },
        { char: "🛵", name: "motor scooter" },
        { char: "🚲", name: "bicycle" },
        { char: "🛴", name: "kick scooter" },
        { char: "🛹", name: "skateboard" },
        { char: "🚀", name: "rocket" },
        { char: "✈️", name: "airplane" },
        { char: "🏖️", name: "beach with umbrella" },
        { char: "🏔️", name: "snow-capped mountain" },
        { char: "🏕️", name: "camping" },
        { char: "🏠", name: "house" },
        { char: "🏰", name: "castle" }
    ],
    objects: [
        { char: "⌚", name: "watch" },
        { char: "📱", name: "mobile phone" },
        { char: "💻", name: "laptop" },
        { char: "⌨️", name: "keyboard" },
        { char: "🖥️", name: "desktop computer" },
        { char: "🖱️", name: "computer mouse" },
        { char: "🖨️", name: "printer" },
        { char: "📷", name: "camera" },
        { char: "🎥", name: "movie camera" },
        { char: "💡", name: "light bulb" },
        { char: "🔦", name: "flashlight" },
        { char: "🕯️", name: "candle" },
        { char: "📕", name: "closed book" },
        { char: "📖", name: "open book" },
        { char: "💰", name: "money bag" },
        { char: "💵", name: "dollar banknote" },
        { char: "💳", name: "credit card" },
        { char: "💎", name: "gem stone" },
        { char: "🔧", name: "wrench" },
        { char: "🔨", name: "hammer" },
        { char: "⛏️", name: "pick" },
        { char: "🔩", name: "nut and bolt" },
        { char: "⚙️", name: "gear" },
        { char: "⛓️", name: "chains" },
        { char: "🔫", name: "pistol" },
        { char: "💣", name: "bomb" },
        { char: "🧨", name: "firecracker" },
        { char: "🪓", name: "axe" },
        { char: "🔪", name: "kitchen knife" },
        { char: "🗡️", name: "dagger" },
        { char: "🛡️", name: "shield" },
        { char: "🗝️", name: "old key" },
        { char: "🔑", name: "key" },
        { char: "🔒", name: "locked" },
        { char: "🔓", name: "unlocked" }
    ],
    symbols: [
        { char: "🏧", name: "ATM sign" },
        { char: "🚮", name: "litter in bin sign" },
        { char: "🚰", name: "potable water" },
        { char: "♿", name: "wheelchair symbol" },
        { char: "🚹", name: "men's room" },
        { char: "🚺", name: "women's room" },
        { char: "🚻", name: "restroom" },
        { char: "🚼", name: "baby symbol" },
        { char: "🚾", name: "water closet" },
        { char: "⚠️", name: "warning" },
        { char: "🚸", name: "children crossing" },
        { char: "⛔", name: "no entry" },
        { char: "🚫", name: "prohibited" },
        { char: "🚳", name: "no bicycles" },
        { char: "🚭", name: "no smoking" },
        { char: "🚯", name: "no littering" },
        { char: "🚱", name: "non-potable water" },
        { char: "🚷", name: "no pedestrians" },
        { char: "📵", name: "no mobile phones" },
        { char: "🔞", name: "no one under 18" },
        { char: "☢️", name: "radioactive" },
        { char: "☣️", name: "biohazard" },
        { char: "⬆️", name: "up arrow" },
        { char: "↗️", name: "up-right arrow" },
        { char: "➡️", name: "right arrow" },
        { char: "↘️", name: "down-right arrow" },
        { char: "⬇️", name: "down arrow" },
        { char: "↙️", name: "down-left arrow" },
        { char: "⬅️", name: "left arrow" },
        { char: "↖️", name: "up-left arrow" },
        { char: "↕️", name: "up-down arrow" },
        { char: "↔️", name: "left-right arrow" },
        { char: "↩️", name: "right arrow curving left" },
        { char: "↪️", name: "left arrow curving right" },
        { char: "🔃", name: "clockwise vertical arrows" },
        { char: "🔄", name: "counterclockwise arrows button" },
        { char: "🔙", name: "BACK arrow" },
        { char: "🔚", name: "END arrow" },
        { char: "🔛", name: "ON! arrow" },
        { char: "🔜", name: "SOON arrow" },
        { char: "🔝", name: "TOP arrow" },
        { char: "🛐", name: "place of worship" },
        { char: "⚛️", name: "atom symbol" },
        { char: "🕉️", name: "om" },
        { char: "✡️", name: "star of david" },
        { char: "☸️", name: "wheel of dharma" },
        { char: "☯️", name: "yin yang" },
        { char: "✝️", name: "latin cross" },
        { char: "☦️", name: "orthodox cross" },
        { char: "☪️", name: "star and crescent" },
        { char: "☮️", name: "peace symbol" },
        { char: "🕎", name: "menorah" },
        { char: "🔯", name: "dotted six-pointed star" },
        { char: "♈", name: "Aries" },
        { char: "♉", name: "Taurus" },
        { char: "♊", name: "Gemini" },
        { char: "♋", name: "Cancer" },
        { char: "♌", name: "Leo" },
        { char: "♍", name: "Virgo" },
        { char: "♎", name: "Libra" },
        { char: "♏", name: "Scorpio" },
        { char: "♐", name: "Sagittarius" },
        { char: "♑", name: "Capricorn" },
        { char: "♒", name: "Aquarius" },
        { char: "♓", name: "Pisces" },
        { char: "⛎", name: "Ophiuchus" },
        { char: "🔀", name: "shuffle tracks button" },
        { char: "🔁", name: "repeat button" },
        { char: "🔂", name: "repeat single button" },
        { char: "▶️", name: "play button" },
        { char: "⏩", name: "fast-forward button" },
        { char: "⏭️", name: "next track button" },
        { char: "⏯️", name: "play or pause button" },
        { char: "◀️", name: "reverse button" },
        { char: "⏪", name: "fast reverse button" },
        { char: "⏮️", name: "last track button" },
        { char: "🔼", name: "upwards button" },
        { char: "⏫", name: "fast up button" },
        { char: "🔽", name: "downwards button" },
        { char: "⏬", name: "fast down button" },
        { char: "⏸️", name: "pause button" },
        { char: "⏹️", name: "stop button" },
        { char: "⏺️", name: "record button" },
        { char: "⏏️", name: "eject button" },
        { char: "🎦", name: "cinema" },
        { char: "🔅", name: "dim button" },
        { char: "🔆", name: "bright button" },
        { char: "📶", name: "antenna bars" },
        { char: "📳", name: "vibration mode" },
        { char: "📴", name: "mobile phone off" },
        { char: "♀️", name: "female sign" },
        { char: "♂️", name: "male sign" },
        { char: "⚕️", name: "medical symbol" },
        { char: "♾️", name: "infinity" },
        { char: "♻️", name: "recycling symbol" },
        { char: "⚜️", name: "fleur-de-lis" },
        { char: "🔱", name: "trident emblem" },
        { char: "📛", name: "name badge" },
        { char: "🔰", name: "Japanese symbol for beginner" },
        { char: "⭕", name: "heavy large circle" },
        { char: "✅", name: "white heavy check mark" },
        { char: "☑️", name: "ballot box with check" },
        { char: "✔️", name: "heavy check mark" },
        { char: "✖️", name: "heavy multiplication x" },
        { char: "❌", name: "cross mark" },
        { char: "❎", name: "cross mark button" },
        { char: "➕", name: "heavy plus sign" },
        { char: "➖", name: "heavy minus sign" },
        { char: "➗", name: "heavy division sign" },
        { char: "➰", name: "curly loop" },
        { char: "➿", name: "double curly loop" },
        { char: "〽️", name: "part alternation mark" },
        { char: "✳️", name: "eight-spoked asterisk" },
        { char: "✴️", name: "eight-pointed star" },
        { char: "❇️", name: "sparkle" },
        { char: "‼️", name: "double exclamation mark" },
        { char: "⁉️", name: "exclamation question mark" },
        { char: "❓", name: "question mark" },
        { char: "❔", name: "white question mark" },
        { char: "❕", name: "white exclamation mark" },
        { char: "❗", name: "exclamation mark" },
        { char: "〰️", name: "wavy dash" },
        { char: "©️", name: "copyright" },
        { char: "®️", name: "registered" },
        { char: "™️", name: "trade mark" }
    ],
    flags: [
        { char: "🏳️", name: "white flag" },
        { char: "🏳️‍🌈", name: "rainbow flag" },
        { char: "🏴", name: "black flag" },
        { char: "🇦🇫", name: "flag: Afghanistan" },
        { char: "🇦🇱", name: "flag: Albania" },
        { char: "🇩🇿", name: "flag: Algeria" },
        { char: "🇦🇷", name: "flag: Argentina" },
        { char: "🇦🇺", name: "flag: Australia" },
        { char: "🇦🇹", name: "flag: Austria" },
        { char: "🇧🇭", name: "flag: Bahrain" },
        { char: "🇧🇩", name: "flag: Bangladesh" },
        { char: "🇧🇪", name: "flag: Belgium" },
        { char: "🇧🇷", name: "flag: Brazil" },
        { char: "🇨🇦", name: "flag: Canada" },
        { char: "🇨🇱", name: "flag: Chile" },
        { char: "🇨🇳", name: "flag: China" },
        { char: "🇨🇴", name: "flag: Colombia" },
        { char: "🇭🇷", name: "flag: Croatia" },
        { char: "🇨🇿", name: "flag: Czechia" },
        { char: "🇩🇰", name: "flag: Denmark" },
        { char: "🇪🇬", name: "flag: Egypt" },
        { char: "🇫🇮", name: "flag: Finland" },
        { char: "🇫🇷", name: "flag: France" },
        { char: "🇩🇪", name: "flag: Germany" },
        { char: "🇬🇷", name: "flag: Greece" },
        { char: "🇮🇳", name: "flag: India" },
        { char: "🇮🇩", name: "flag: Indonesia" },
        { char: "🇮🇷", name: "flag: Iran" },
        { char: "🇮🇶", name: "flag: Iraq" },
        { char: "🇮🇪", name: "flag: Ireland" },
        { char: "🇮🇱", name: "flag: Israel" },
        { char: "🇮🇹", name: "flag: Italy" },
        { char: "🇯🇵", name: "flag: Japan" },
        { char: "🇯🇴", name: "flag: Jordan" },
        { char: "🇰🇼", name: "flag: Kuwait" },
        { char: "🇱🇧", name: "flag: Lebanon" },
        { char: "🇱🇾", name: "flag: Libya" },
        { char: "🇲🇾", name: "flag: Malaysia" },
        { char: "🇲🇽", name: "flag: Mexico" },
        { char: "🇲🇦", name: "flag: Morocco" },
        { char: "🇳🇱", name: "flag: Netherlands" },
        { char: "🇳🇿", name: "flag: New Zealand" },
        { char: "🇳🇬", name: "flag: Nigeria" },
        { char: "🇳🇴", name: "flag: Norway" },
        { char: "🇴🇲", name: "flag: Oman" },
        { char: "🇵🇰", name: "flag: Pakistan" },
        { char: "🇵🇸", name: "flag: Palestinian Territories" },
        { char: "🇵🇭", name: "flag: Philippines" },
        { char: "🇵🇱", name: "flag: Poland" },
        { char: "🇵🇹", name: "flag: Portugal" },
        { char: "🇶🇦", name: "flag: Qatar" },
        { char: "🇷🇴", name: "flag: Romania" },
        { char: "🇷🇺", name: "flag: Russia" },
        { char: "🇸🇦", name: "flag: Saudi Arabia" },
        { char: "🇸🇬", name: "flag: Singapore" },
        { char: "🇿🇦", name: "flag: South Africa" },
        { char: "🇰🇷", name: "flag: South Korea" },
        { char: "🇪🇸", name: "flag: Spain" },
        { char: "🇸🇪", name: "flag: Sweden" },
        { char: "🇨🇭", name: "flag: Switzerland" },
        { char: "🇸🇾", name: "flag: Syria" },
        { char: "🇹🇳", name: "flag: Tunisia" },
        { char: "🇹🇷", name: "flag: Turkey" },
        { char: "🇺🇦", name: "flag: Ukraine" },
        { char: "🇦🇪", name: "flag: United Arab Emirates" },
        { char: "🇬🇧", name: "flag: United Kingdom" },
        { char: "🇺🇸", name: "flag: United States" },
        { char: "🇾🇪", name: "flag: Yemen" }
    ]
};
